// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bump } from "./Bump";
import type { Oid } from "./Oid";
import type { PullMode } from "./PullMode";
import type { ResetMode } from "./ResetMode";
import type { SyncPlan } from "./SyncPlan";

/**
 * What to do to a repository.
 */
export type Action = { "type": "Fetch", "value": { prune: boolean, tags: boolean, } } | { "type": "Pull", "value": { mode: PullMode, } } | { "type": "Push", "value": { 
/**
 * `Some(remote)` sets the upstream to that remote, for a branch that
 * has none. `None` pushes to the configured upstream.
 */
set_upstream: string | null, force_with_lease: boolean, } } | { "type": "Checkout", "value": { rev: string, create: boolean, } } | { "type": "Commit", "value": { 
/**
 * The template before the planner resolves it, the rendered message
 * afterwards.
 */
message: string, stage_all: boolean, 
/**
 * Skip the repository's own hooks.
 */
no_verify: boolean, } } | { "type": "Stash", "value": { include_untracked: boolean, } } | { "type": "StashPop" } | { "type": "Branch", "value": { name: string, 
/**
 * Where to start it. `None` is the current `HEAD`.
 */
from: string | null, } } | { "type": "Reset", "value": { to: Oid, mode: ResetMode, } } | { "type": "SyncDefault", "value": { mode: PullMode, 
/**
 * `None` in a template, `Some` once resolved for one repository.
 */
plan: SyncPlan | null, } } | { "type": "DevTag", "value": { 
/**
 * The series: `dev`, `rc`, whatever the team writes.
 */
channel: string, 
/**
 * Where a *new* series starts, from the newest release.
 */
bump: Bump, 
/**
 * `None` in a template, `Some` once derived for one repository.
 */
name: string | null, 
/**
 * Publish to this remote. `None` creates it locally only.
 */
push: string | null, } } | { "type": "Custom", "value": { args: Array<string>, 
/**
 * Does this reach the network, and so take the network semaphore?
 * Defaults to `true` when unstated.
 */
network: boolean, 
/**
 * Can it move `HEAD` or create local history? Defaults to `true`
 * when unstated.
 */
mutating: boolean, } };
