// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { RepoId } from "./RepoId";

/**
 * header.
 */
export type ActionVariant = { action: Action, repos: Array<RepoId>, };
