// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bump } from "./Bump";
import type { Oid } from "./Oid";
import type { PullMode } from "./PullMode";
import type { ResetMode } from "./ResetMode";
import type { SyncPlan } from "./SyncPlan";

export type Action = { "type": "Fetch", "value": { prune: boolean, tags: boolean, } } | { "type": "Pull", "value": { mode: PullMode, } } | { "type": "Push", "value": { set_upstream: string | null, force_with_lease: boolean, } } | { "type": "Checkout", "value": { rev: string, create: boolean, } } | { "type": "Commit", "value": { message: string, stage_all: boolean, no_verify: boolean, } } | { "type": "Stash", "value": { include_untracked: boolean, } } | { "type": "StashPop" } | { "type": "Branch", "value": { name: string, from: string | null, } } | { "type": "Reset", "value": { to: Oid, mode: ResetMode, } } | { "type": "SyncDefault", "value": { mode: PullMode, plan: SyncPlan | null, } } | { "type": "DevTag", "value": { channel: string, bump: Bump, name: string | null, push: string | null, } } | { "type": "Custom", "value": { args: Array<string>, network: boolean, mutating: boolean, } };
