// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { RepoId } from "./RepoId";

/**
 * One distinct resolved action and the repositories that got it.
 *
 * Usually a single entry. More than one means resolution produced genuinely
 * different commands, and the plan has to say so — a header reading "Push 31
 * repos" while three of them push somewhere else is the kind of lie a plan
 * exists to prevent.
 */
export type ActionVariant = { action: Action, repos: Array<RepoId>, };
