// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single value summarising a snapshot, for display and sorting only.
 *
 * Derived, never stored; declaration order is the sort priority, worst first.
 */
export type Badge = "Conflict" | "InProgress" | "Diverged" | "Behind" | "Ahead" | "Dirty" | "Staged" | "Clean" | "Unknown";
