// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a batch turned out.
 */
export type BatchSummary = { ok: number, failed: number, skipped: number, cancelled: number, 
/**
 * Still queued or running. Non-zero only for a summary taken mid-flight.
 */
pending: number, duration: number, };
