// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { BatchId } from "./BatchId";
import type { JobId } from "./JobId";
import type { JobOrigin } from "./JobOrigin";

/**
 * One user gesture: an action, a selection, and the jobs it produced.
 */
export type Batch = { id: BatchId, 
/**
 * The **template** the plan was built from. Each job carries its own
 * resolved action, which may differ per repository.
 */
action: Action, origin: JobOrigin, jobs: Array<JobId>, 
/**
 * The batch this one undoes, if it is an undo.
 *
 * Marked so it can be excluded: never undo an undo. One level, explicit,
 * recent — a stack would need a history the tool deliberately does not
 * keep, and a second undo of the same work is a `reset --hard` whose target
 * nobody chose.
 */
undoes: BatchId | null, started_at: number, finished_at: number | null, };
