// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

/**
 * A structured error, never a stringified `Debug`.
 *
 * `kind` is for the UI to branch on; `message` is for a person to read. A
 * `Debug`-formatted Rust error is neither — it cannot be matched on without
 * parsing prose, and it shows the user type names.
 */
export type BridgeError = { kind: ErrorKind, message: string, };
