// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which component the next series starts from.
 */
export type Bump = "Major" | "Minor" | "Patch";
