// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomCommand } from "./CustomCommand";

/**
 * Everything persisted between launches.
 */
export type Config = { roots: Array<string>, 
/**
 * Application to open a repository in, by name as `open -a` understands
 * it — "Visual Studio Code", "Zed". `None` falls back to `$EDITOR`.
 */
editor: string | null, 
/**
 * Application to open a repository's terminal in, by name as `open -a`
 * understands it — "Ghostty", "iTerm". `None` is resolved by
 * `handoff::terminal_app`, which always has an answer.
 */
terminal: string | null, custom: Array<CustomCommand>, };
