// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A deliberate obstacle between a plan and running it.
 */
export type ConfirmGuard = { "type": "TypeCount", "value": number } | { "type": "Acknowledge", "value": string };
