// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomCommand } from "./CustomCommand";

export type Config = { roots: Array<string>, editor: string | null, terminal: string | null, fetch_interval_secs: number | null, custom: Array<CustomCommand>, };
