// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomCommand = { name: string, args: Array<string>, network: boolean, mutating: boolean, acknowledged: boolean, };
