// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One saved custom command.
 */
export type CustomCommand = { name: string, 
/**
 * An argv vector, **never a shell string**.
 */
args: Array<string>, 
/**
 * Which semaphore it takes, and whether `head_before` is recorded.
 */
network: boolean, mutating: boolean, 
/**
 * Persisted per definition: an edit to `args` clears it.
 */
acknowledged: boolean, };
