// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something the walk could not read. On macOS this is almost always TCC: an
 * unsigned app scanning `~/Documents` gets permission denied per directory,
 * indistinguishable from an empty tree unless reported.
 */
export type DiscoveryError = { "type": "UnusableRoot", "value": string } | { "type": "Unreadable", "value": { path: string, reason: string, } } | { "type": "MoreUnreadable", "value": number };
