// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something the walk could not read.
 *
 * Reported to the caller rather than only logged, because on macOS this is
 * almost always TCC: an unsigned app scanning `~/Documents` gets permission
 * denied per directory and finds nothing, which is indistinguishable from an
 * empty working set unless somebody says so. That message is the highest-value
 * error in the application, and it cannot be written without this.
 */
export type DiscoveryError = { "type": "UnusableRoot", "value": string } | { "type": "Unreadable", "value": { path: string, reason: string, } } | { "type": "MoreUnreadable", "value": number };
