// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";
import type { BatchSummary } from "./BatchSummary";
import type { DiscoveryError } from "./DiscoveryError";
import type { JobId } from "./JobId";
import type { JobOrigin } from "./JobOrigin";
import type { JobState } from "./JobState";
import type { LogLine } from "./LogLine";
import type { RepoId } from "./RepoId";
import type { RepoSnapshot } from "./RepoSnapshot";
import type { ScanId } from "./ScanId";

export type Event = { "type": "ReposUpserted", "value": Array<RepoSnapshot> } | { "type": "ReposRemoved", "value": Array<RepoId> } | { "type": "ScanProgress", "value": { scan: ScanId, found: number, probed: number, } } | { "type": "ScanDone", "value": { scan: ScanId, errors: Array<DiscoveryError>, } } | { "type": "JobStateChanged", "value": { id: JobId, batch: BatchId | null, origin: JobOrigin, repo: RepoId, state: JobState, } } | { "type": "JobLogAppended", "value": { id: JobId, lines: Array<LogLine>, } } | { "type": "BatchDone", "value": { id: BatchId, summary: BatchSummary, } } | { "type": "Lagged" };
