// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailureKind } from "./FailureKind";

/**
 * A failure, explained.
 */
export type Explanation = { kind: FailureKind, 
/**
 * What to do, when there is a useful answer.
 */
remedy: string | null, 
/**
 * The line from git that this was read off.
 */
evidence: string, };
