// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of thing went wrong.
 */
export type FailureKind = "NonFastForward" | "ProtectedBranch" | "Auth" | "Unreachable" | "LeaseStale" | "Conflict" | "HookRejected" | "RefNotFound" | "TagExists" | "WouldOverwrite" | "Unknown";
