// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FetchSchedule } from "./FetchSchedule";

/**
 * Automatic-fetch bookkeeping for one repository.
 *
 * Engine state rather than a fact on disk, but it rides in the snapshot: that
 * is the single object shipped to every surface, and a parallel stream for
 * this would buy nothing but joins.
 */
export type FetchHealth = { last_attempt: number | null, 
/**
 * Last success **by this tool's scheduler**. Compare
 * [`crate::Upstream::last_fetch`], which moves for any fetch by anyone.
 */
last_success: number | null, schedule: FetchSchedule, };
