// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FetchSchedule } from "./FetchSchedule";

export type FetchHealth = { last_attempt: number | null, last_success: number | null, schedule: FetchSchedule, };
