// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FetchStatus } from "./FetchStatus";

export type FetchCell = { status: FetchStatus, problem: boolean, detail: string | null, };
