// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fetch column, phrased for a grid. The decision is
 * `RepoSnapshot::fetch_status`, shared with the CLI; only the phrasing is
 * here.
 */
export type FetchCell = { text: string, 
/**
 * The grid offers "Fetch now" on exactly these.
 */
problem: boolean, 
/**
 * The tooltip: the quarantine's error, or the failure count.
 */
detail: string | null, };
