// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FetchStatus = { "type": "NoRemote" } | { "type": "Off" } | { "type": "Quarantined", "value": { reason: string, } } | { "type": "BackingOff", "value": { until: number, failures: number, } } | { "type": "Fetched", "value": { at: number, } } | { "type": "Never" };
