// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fetch column, phrased for a grid.
 *
 * The *decision* is `RepoSnapshot::fetch_status`, shared with the CLI. Only
 * the phrasing is here, and it differs on purpose: this cell has a tooltip and
 * a button behind it, so it says the short thing and puts the reason in
 * `detail`, where the CLI has one line and must inline it.
 */
export type FetchCell = { text: string, 
/**
 * Something is wrong and the user can act on it — the grid offers
 * "Fetch now" on exactly these.
 */
problem: boolean, 
/**
 * The tooltip: the quarantine's error, or the failure count.
 */
detail: string | null, };
