// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FetchSchedule = { "type": "Due", "value": number } | { "type": "BackingOff", "value": { until: number, failures: number, } } | { "type": "Quarantined", "value": { since: number, last_error: string, } } | { "type": "Disabled" };
