// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Oid } from "./Oid";

export type Head = { "type": "Branch", "value": string } | { "type": "Detached", "value": Oid } | { "type": "Unborn", "value": string };
