// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A multi-step git operation the user left half-finished.
 */
export type InProgress = "Merge" | "Rebase" | "CherryPick" | "Revert" | "Bisect";
