// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A multi-step git operation the user left half-finished.
 *
 * Every one of these makes most mutating actions unsafe, which is why it is a
 * first-class fact rather than something inferred from a dirty worktree.
 */
export type InProgress = "Merge" | "Rebase" | "CherryPick" | "Revert" | "Bisect";
