// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { BatchId } from "./BatchId";
import type { JobId } from "./JobId";
import type { JobOrigin } from "./JobOrigin";
import type { JobState } from "./JobState";
import type { LogLine } from "./LogLine";
import type { Oid } from "./Oid";
import type { RepoId } from "./RepoId";
import type { StepRun } from "./StepRun";

/**
 * One action against one repository.
 */
export type Job = { id: JobId, 
/**
 * `None` for a background job: the fetch scheduler's jobs belong to no
 * user batch.
 */
batch: BatchId | null, origin: JobOrigin, repo: RepoId, 
/**
 * Resolved for **this** repository, not the batch's template.
 */
action: Action, state: JobState, 
/**
 * Populated from [`Action::steps`] when the job is created, so the plan and
 * the transcript describe the same commands.
 */
steps: Array<StepRun>, 
/**
 * `HEAD` immediately before a mutating job. `None` for a non-mutating
 * action or an unborn branch. This one field is what makes undo real.
 */
head_before: Oid | null, 
/**
 * Where the job left `HEAD`, recorded the same way and for the same
 * reason.
 *
 * `head_before` alone cannot tell an undo whether it is safe: a repository
 * whose HEAD is not `head_before` has *either* been changed by this job, or
 * been changed by this job and then committed on top of. Undoing the second
 * discards work nobody asked to lose.
 */
head_after: Oid | null, 
/**
 * The branch checked out when the job was planned.
 *
 * `None` for a detached HEAD, which has no branch to return to. Stamped
 * from the snapshot rather than read with a second `rev-parse`: the
 * snapshot already knows and the staleness precondition guarantees it is
 * current, so a subprocess per mutating job would be paid on every commit
 * and pull to serve only a checkout's undo.
 */
branch_before: string | null, 
/**
 * The whole transcript, interleaved and ordered. `StepRun::log` indexes
 * into it.
 */
log: Array<LogLine>, started_at: number | null, finished_at: number | null, };
