// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { BatchId } from "./BatchId";
import type { JobId } from "./JobId";
import type { JobOrigin } from "./JobOrigin";
import type { JobState } from "./JobState";
import type { LogLine } from "./LogLine";
import type { Oid } from "./Oid";
import type { RepoId } from "./RepoId";
import type { StepRun } from "./StepRun";

/**
 * One action against one repository.
 */
export type Job = { id: JobId, 
/**
 * `None` for a background job: the fetch scheduler's jobs belong to no
 * user batch.
 */
batch: BatchId | null, origin: JobOrigin, repo: RepoId, 
/**
 * Resolved for **this** repository, not the batch's template.
 */
action: Action, state: JobState, 
/**
 * Populated from [`Action::steps`] when the job is created.
 */
steps: Array<StepRun>, 
/**
 * `HEAD` immediately before a mutating job. `None` for a non-mutating
 * action or an unborn branch.
 */
head_before: Oid | null, 
/**
 * Where the job left `HEAD`.
 */
head_after: Oid | null, 
/**
 * The branch checked out when the job was planned. `None` for a detached HEAD.
 */
branch_before: string | null, 
/**
 * The whole transcript, interleaved and ordered. `StepRun::log` indexes
 * into it.
 */
log: Array<LogLine>, started_at: number | null, finished_at: number | null, };
