// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier for one job. Allocated by the engine monotonically, so it also
 * orders jobs by the moment they were created.
 */
export type JobId = number;
