// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who asked for this job.
 *
 * Selects the scheduler's priority class, and whether the job appears in the
 * drawer unbidden. The background fetch scheduler is the only producer of
 * `Background`.
 */
export type JobOrigin = "User" | "Background";
