// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkipReason } from "./SkipReason";

export type JobState = { "type": "Queued" } | { "type": "Running" } | { "type": "Ok" } | { "type": "Failed", "value": { code: number, } } | { "type": "Cancelled" } | { "type": "Skipped", "value": { why: SkipReason, } };
