// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stream } from "./Stream";

/**
 * One line of a job's transcript.
 */
export type LogLine = { at: number, stream: Stream, 
/**
 * Lossy UTF-8: git can write non-UTF-8 filenames into its error messages.
 */
text: string, };
