// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a menu item asks the window to do.
 *
 * An enum rather than loose string ids, generated into TypeScript like
 * everything else that crosses the boundary: adding an item then fails
 * to compile on the other side until it is handled, which is the only
 * reliable way to keep a menu from growing a dead entry.
 */
export type MenuCommand = "AddRoot" | "FocusFilter" | "SelectAll" | "ClearSelection" | "Refresh" | "RescanRoots" | "ToggleDrawer" | "Fetch" | "PullFfOnly" | "PullRebase" | "PullMerge" | "SortByName" | "SortByPath" | "SortByBranch" | "SortByState" | "SortByStatus" | "SortByFetch";
