// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a menu item asks the window to do.
 */
export type MenuCommand = "AddRoot" | "FocusFilter" | "SelectAll" | "ClearSelection" | "Refresh" | "RescanRoots" | "ToggleDrawer" | "Fetch" | "PullFfOnly" | "PullRebase" | "PullMerge" | "SortByName" | "SortByPath" | "SortByBranch" | "SortByState" | "SortByStatus" | "SortByFetch";
