// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Outage } from "./Outage";

/**
 * Whether this machine can reach anything at all.
 *
 * A fact about the machine, not about a repository, and it is the reason the
 * two are kept apart: a repository that keeps refusing is quarantined, and a
 * machine with no network is simply waited for.
 */
export type Network = { "type": "Up" } | { "type": "Down", "value": { since: number, cause: Outage, } };
