// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What put the network verdict down, which is also what lifts it — and so
 * what the user is told is happening in the meantime.
 */
export type Outage = "NoRoute" | "Unreachable";
