// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The template substitution set.
 *
 * Served rather than restated on the other side: help text that repeats a
 * table is help text that goes stale.
 */
export type Placeholder = { token: string, means: string, };
