// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfirmGuard } from "./ConfirmGuard";
import type { PlanRow } from "./PlanRow";
import type { PlanVariant } from "./PlanVariant";

/**
 * A plan reduced to the strings a surface displays, and nothing else.
 *
 * Deliberately free of `Action` and `SkipReason`: a surface that could reach
 * the domain types would be able to phrase them itself, and that drift is what
 * this type exists to make impossible.
 */
export type PlanView = { 
/**
 * `Pull 47 repos (rebase)` — the whole selection, eligible or not.
 */
headline: string, 
/**
 * `47 of 100 selected`, when the selection narrowed the working set.
 */
selection_note: string | null, 
/**
 * The heading over [`Self::variants`], or `None` when there are none.
 *
 * Here rather than in each surface because it is prose *and* conditional,
 * which is the combination that goes wrong: the fixed plural read
 * "resolved to 1 different commands" for every plan whose action shows its
 * command unconditionally — a case `show_commands` newly made reachable.
 */
variants_note: string | null, 
/**
 * What will run. `None` when nothing qualifies.
 */
eligible: PlanRow | null, 
/**
 * What will not, grouped by reason and descending by count.
 */
skips: Array<PlanRow>, 
/**
 * Every distinct resolved command, when resolution produced more than one.
 * Empty otherwise — see [`Plan::action_variants`].
 */
variants: Array<PlanVariant>, 
/**
 * The confirm control's label, stated as its effect: `Pull 31 repos
 * (rebase)`, never `Confirm`. `None` means there must be no control.
 */
confirm_label: string | null, 
/**
 * Something the user must do before the control works at all.
 *
 * Reserved for the genuinely irreversible. Everything else stays neutral,
 * so the distinction keeps its meaning: danger styling that shows up on
 * ordinary work is wallpaper within a week, and then it is not there on
 * the day it matters.
 */
confirm_guard: ConfirmGuard | null, 
/**
 * Why there is nothing to do, when there is nothing to do.
 */
empty_note: string | null, 
/**
 * See [`Plan::warning`].
 */
warning: string | null, };
