// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoId } from "./RepoId";

/**
 * One resolved command, already rendered.
 */
export type PlanVariant = { 
/**
 * `git push --set-upstream origin`, as [`Action`] renders itself.
 */
command: string, 
/**
 * Who this one is for: the repository's name when it is the only one, and
 * the count otherwise.
 *
 * A bare count is the wrong thing to show when every command has exactly
 * one repository, which is the normal shape for a *derived* name — forty
 * rows reading `1` beside forty different tags, with no way to tell which
 * is which. Composed here so the CLI and the sheet cannot disagree.
 */
label: string, repos: Array<RepoId>, };
