// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoId } from "./RepoId";

/**
 * One line of a plan: a count, what happens to it, and why.
 */
export type PlanRow = { count: number, 
/**
 * `will pull`, or `skipped`.
 */
phrase: string, 
/**
 * `behind, clean, upstream present`, or `already up to date`.
 */
detail: string, 
/**
 * Expandable to the repositories themselves, so a surprising count can be
 * checked rather than trusted.
 */
repos: Array<RepoId>, };
