// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Plan } from "./Plan";
import type { PlanView } from "./PlanView";

/**
 * What a batch would do, plus the strings that describe it.
 */
export type PlanSheet = { 
/**
 * Opaque to the frontend; goes back to [`start_batch`] unmodified.
 */
plan: Plan, view: PlanView, };
