// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Plan } from "./Plan";
import type { PlanView } from "./PlanView";

export type PlanSheet = { plan: Plan, view: PlanView, };
