// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { RepoId } from "./RepoId";
import type { SkipReason } from "./SkipReason";

export type Plan = { action: Action, eligible: Array<[RepoId, Action]>, skipped: Array<[RepoId, SkipReason]>, considered: number, warning: string | null, };
