// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfirmGuard } from "./ConfirmGuard";
import type { PlanRow } from "./PlanRow";
import type { PlanVariant } from "./PlanVariant";

export type PlanView = { headline: string, selection_note: string | null, variants_note: string | null, eligible: PlanRow | null, skips: Array<PlanRow>, variants: Array<PlanVariant>, confirm_label: string | null, confirm_guard: ConfirmGuard | null, empty_note: string | null, warning: string | null, };
