// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Plan } from "./Plan";
import type { PlanView } from "./PlanView";

/**
 * What a batch would do, plus the strings that describe it.
 *
 * Both, in one round trip, because they are always wanted together: the sheet
 * shows the view and hands the plan straight back to [`start_batch`]. Deriving
 * the view on this side instead would mean the GUI phrasing "31 will pull"
 * itself, leaving it free to drift from the CLI.
 */
export type PlanSheet = { 
/**
 * The domain object. Opaque to the frontend; it goes back to
 * [`start_batch`] unmodified.
 */
plan: Plan, view: PlanView, };
