// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoId } from "./RepoId";

export type PlanRow = { count: number, phrase: string, detail: string, repos: Array<RepoId>, };
