// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Remote = { 
/**
 * `"origin"`.
 */
name: string, 
/**
 * Host parsed from the configured URL. `None` for a path remote or an
 * unparseable URL.
 */
host: string | null, 
/**
 * The repository's page on that host, derived from the same URL. `None`
 * wherever `host` is, and for a URL that names no repository.
 */
web: string | null, };
