// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Remote = { 
/**
 * `"origin"`.
 */
name: string, 
/**
 * Host parsed from the configured URL. `None` for a path remote or an
 * unparseable URL — this is a concurrency bucket key and never a
 * correctness input, so a miss costs throughput and nothing else.
 */
host: string | null, };
