// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FetchHealth } from "./FetchHealth";
import type { Head } from "./Head";
import type { InProgress } from "./InProgress";
import type { Oid } from "./Oid";
import type { ProbeOutcome } from "./ProbeOutcome";
import type { Remote } from "./Remote";
import type { RepoId } from "./RepoId";
import type { RepoKind } from "./RepoKind";
import type { Upstream } from "./Upstream";
import type { WorkTree } from "./WorkTree";

/**
 * Everything the tool knows about one repository at one instant.
 */
export type RepoSnapshot = { id: RepoId, path: string, kind: RepoKind, head: Head, 
/**
 * The commit `HEAD` resolves to.
 *
 * `None` for an unborn branch.
 */
head_oid: Oid | null, upstream: Upstream | null, 
/**
 * Fetchable targets. `Remote::host` is the per-host concurrency bucket key
 * for automatic fetching.
 */
remotes: Array<Remote>, work: WorkTree, op: InProgress | null, stashes: number, 
/**
 * Auto-fetch bookkeeping. Engine-maintained, never probed.
 */
fetch: FetchHealth, probed_at: number, outcome: ProbeOutcome, 
/**
 * Restored from a previous run's cache and not yet re-read.
 */
from_cache: boolean, 
/**
 * A watcher is covering this repository.
 */
watched?: boolean, };
