// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Badge } from "./Badge";
import type { FetchCell } from "./FetchCell";
import type { FetchHealth } from "./FetchHealth";
import type { Head } from "./Head";
import type { InProgress } from "./InProgress";
import type { Oid } from "./Oid";
import type { ProbeOutcome } from "./ProbeOutcome";
import type { Remote } from "./Remote";
import type { RepoId } from "./RepoId";
import type { RepoKind } from "./RepoKind";
import type { Upstream } from "./Upstream";
import type { WorkTree } from "./WorkTree";

/**
 * A snapshot plus what the grid derives from it.
 *
 * `#[serde(flatten)]` so the wire shape is one flat object — a row is a
 * repository with two extra columns, not a repository wrapped in something.
 */
export type RepoRow = { badge: Badge, 
/**
 * The badge as a word, from `Badge`'s `Display`.
 *
 * Carried rather than derived on the other side, which had been
 * lowercasing the variant name — a transliteration that holds only while
 * every variant is a single word, and `InProgress` lowercases to
 * `inprogress`. Phrasing a domain value is Rust's job here as everywhere
 * else, and this is also the CSS class, so the two cannot disagree.
 */
badge_label: string, 
/**
 * Not verified by the running process, or verified too long ago.
 *
 * Derived here rather than in the grid for the same reason `badge` is, and
 * with an extra one: this is the *same* predicate the `SnapshotStale`
 * precondition uses, so a row shown as current can never be one an action
 * then refuses as stale. Two spellings of "stale" would let the tool
 * contradict itself on screen.
 */
stale: boolean, 
/**
 * Sort priority, worst first.
 *
 * Sent as a number because the ordering lives in the declaration order of
 * [`Badge`], which a TypeScript string union cannot express. A hand-kept
 * array of badge names on the other side would be that ordering written
 * down twice, and the second copy would be the one that rots.
 */
badge_rank: number, 
/**
 * The compact status column, from `RepoSnapshot::status_line`.
 *
 * The same string the CLI's STATUS column shows, because it is the same
 * column. It was written twice — once here in Rust and once in
 * `columns.ts` — and the two had already parted company over what a bare
 * repository with an upstream should read as.
 */
status: string, fetch_cell: FetchCell, id: RepoId, path: string, kind: RepoKind, head: Head, 
/**
 * The commit `HEAD` resolves to.
 *
 * [`Head`] says *what* HEAD is; this says *where* it points, which for a
 * branch the head itself does not carry. `None` for an unborn branch.
 *
 * Kept for undo: deciding whether somebody has committed on top of a job's
 * result means comparing where HEAD is now against where the job left it.
 */
head_oid: Oid | null, upstream: Upstream | null, 
/**
 * Fetchable targets. `Remote::host` is the per-host concurrency bucket key
 * for automatic fetching.
 */
remotes: Array<Remote>, work: WorkTree, op: InProgress | null, stashes: number, 
/**
 * Auto-fetch bookkeeping. Engine-maintained, never probed.
 */
fetch: FetchHealth, probed_at: number, outcome: ProbeOutcome, 
/**
 * Restored from a previous run's cache and not yet re-read.
 *
 * Age cannot stand in for this. A cache written five seconds ago still
 * describes a repository nothing watched while the application was closed,
 * and "the user committed in a terminal, then relaunched" is exactly the
 * case an age test lets through.
 */
from_cache: boolean, 
/**
 * A watcher is covering this repository.
 *
 * Never persisted: watching is a fact about the running process, and a
 * cache claiming coverage would let a relaunch act on facts nothing had
 * checked since the last run.
 *
 * It exists for [`Self::is_stale`]. Age alone means a repository nobody
 * touches goes stale by sitting still, so thirty seconds after launch every
 * action on a current row is refused with "refresh first".
 */
watched?: boolean, };
