// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Badge } from "./Badge";
import type { FetchCell } from "./FetchCell";
import type { FetchHealth } from "./FetchHealth";
import type { Head } from "./Head";
import type { InProgress } from "./InProgress";
import type { Oid } from "./Oid";
import type { ProbeOutcome } from "./ProbeOutcome";
import type { Remote } from "./Remote";
import type { RepoId } from "./RepoId";
import type { RepoKind } from "./RepoKind";
import type { Upstream } from "./Upstream";
import type { WorkTree } from "./WorkTree";

/**
 * A snapshot plus what the grid derives from it. `#[serde(flatten)]` keeps
 * the wire shape one flat object: a row is a repository with extra columns.
 */
export type RepoRow = { badge: Badge, 
/**
 * The badge as a word, from `Badge`'s `Display`. Also the CSS class.
 */
badge_label: string, 
/**
 * Not verified by the running process, or verified too long ago. The
 * same predicate the `SnapshotStale` precondition uses.
 */
stale: boolean, 
/**
 * Sort priority, worst first. A number because the ordering is
 * [`Badge`]'s declaration order, which a TypeScript string union cannot
 * express.
 */
badge_rank: number, 
/**
 * The compact status column, from `RepoSnapshot::status_line` — the
 * same string the CLI's STATUS column shows.
 */
status: string, fetch_cell: FetchCell, id: RepoId, path: string, kind: RepoKind, head: Head, 
/**
 * The commit `HEAD` resolves to.
 *
 * `None` for an unborn branch.
 */
head_oid: Oid | null, upstream: Upstream | null, 
/**
 * Fetchable targets. `Remote::host` is the per-host concurrency bucket key
 * for automatic fetching.
 */
remotes: Array<Remote>, work: WorkTree, op: InProgress | null, stashes: number, 
/**
 * Auto-fetch bookkeeping. Engine-maintained, never probed.
 */
fetch: FetchHealth, probed_at: number, outcome: ProbeOutcome, 
/**
 * Restored from a previous run's cache and not yet re-read.
 */
from_cache: boolean, 
/**
 * A watcher is covering this repository.
 */
watched?: boolean, };
