// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoId } from "./RepoId";

export type RepoKind = { "type": "Normal" } | { "type": "Bare" } | { "type": "Worktree", "value": { main: RepoId, } } | { "type": "Submodule", "value": { parent: RepoId, } };
