// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A repository's identity: its canonicalized absolute path.
 */
export type RepoId = string;
