// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoId } from "./RepoId";

/**
 * Adjacent tagging (`{"type": ..., "value": ...}`) rather than internal, which
 * cannot represent a newtype variant wrapping a string. One uniform shape
 * across every enum is worth more to the TypeScript generator than a flatter
 * one for the struct variants. Enums whose variants are all unit-valued keep
 * serde's default plain-string form.
 */
export type RepoKind = { "type": "Normal" } | { "type": "Bare" } | { "type": "Worktree", "value": { main: RepoId, } } | { "type": "Submodule", "value": { parent: RepoId, } };
