// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A repository's identity: its canonicalized absolute path.
 *
 * Canonicalized once, at construction, and never again. Every later
 * comparison, map key and selection is then a plain path comparison — no
 * filesystem access, and no chance of two ids for one repository.
 */
export type RepoId = string;
