// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far back a reset takes the working tree.
 */
export type ResetMode = "Soft" | "Hard";
