// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sent as a plain number, not ts-rs's default `bigint` for `u64`: Tauri's IPC
 * is JSON, `serde_json` writes a number, and JavaScript reads one. A generated
 * type that says `bigint` would be a lie of exactly the kind generating them is
 * meant to prevent. Session counters never approach 2^53.
 */
export type ScanId = number;
