// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoId } from "./RepoId";

/**
 * How a batch chooses its repositories.
 *
 * The filter grammar is [`git_scylla_core::Filter`], reused verbatim from
 * `scan --filter`. Not a convenience: the CLI and the GUI must share **one**
 * parser, and the cheapest guarantee is that only one exists.
 */
export type Selection = { "type": "All" } | { "type": "Ids", "value": Array<RepoId> } | { "type": "Filter", "value": string };
