// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InProgress } from "./InProgress";

/**
 * Why a repository was left out of a batch.
 */
export type SkipReason = { "type": "UpToDate" } | { "type": "NoUpstream" } | { "type": "UpstreamGone" } | { "type": "DirtyWorktree" } | { "type": "OperationInProgress", "value": InProgress } | { "type": "DetachedHead" } | { "type": "UnbornBranch" } | { "type": "BareRepo" } | { "type": "Diverged" } | { "type": "NoRemote" } | { "type": "SnapshotStale" } | { "type": "NotSelected" } | { "type": "RefNotFound", "value": string } | { "type": "NoStash" } | { "type": "NotUndoable", "value": string } | { "type": "NoDefaultBranch" } | { "type": "HeadMoved" };
