// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoId } from "./RepoId";
import type { SkipReason } from "./SkipReason";

/**
 * Skips sharing one reason, expandable to the repository list.
 */
export type SkipGroup = { reason: SkipReason, repos: Array<RepoId>, };
