// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pass } from "./Pass";
import type { Step } from "./Step";
import type { StepState } from "./StepState";

export type StepRun = { step: Step, pass: Pass, state: StepState, log: { start: number, end: number, }, };
