// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pass } from "./Pass";
import type { Step } from "./Step";
import type { StepState } from "./StepState";

/**
 * One executed step, and where its output sits in the job's transcript.
 */
export type StepRun = { step: Step, pass: Pass, state: StepState, 
/**
 * A range into [`crate::Job::log`], so the transcript stays one ordered
 * stream while remaining attributable per step. A slice rather than a
 * nested `Vec` because the ordering across steps is the thing a reader
 * needs, and copies of it would drift.
 */
log: { start: number, end: number, }, };
