// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `git` invocation, with the command that closes what it opened.
 *
 * `compensate` runs after the forward pass, in reverse order, whether the
 * job succeeded or failed.
 */
export type Step = { argv: Array<string>, compensate: Array<string> | null, };
