// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to one step.
 */
export type StepState = { "type": "Pending" } | { "type": "Running" } | { "type": "Ok" } | { "type": "Failed", "value": { code: number, } } | { "type": "Cancelled" } | { "type": "NotRun" };
