// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pass } from "./Pass";
import type { Step } from "./Step";
import type { StepState } from "./StepState";

/**
 * One executed step, and where its output sits in the job's transcript.
 */
export type StepRun = { step: Step, pass: Pass, state: StepState, 
/**
 * A range into [`crate::Job::log`].
 */
log: { start: number, end: number, }, };
