// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One repository's answer to "sync the default branch".
 */
export type SyncPlan = { 
/**
 * This repository's own default branch — `main` here, `master` there.
 */
default: string, 
/**
 * The branch to come back to, by name — never `-`.
 */
back_to: string, 
/**
 * Stash first, when there is tracked work in the way of the switch.
 */
stash: boolean, };
