// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";
import type { BatchSummary } from "./BatchSummary";
import type { Event } from "./Event";
import type { RepoRow } from "./RepoRow";

/**
 * What the webview receives: `Event`, except snapshots arrive as grid rows
 * and a finished batch carries its rendered summary line.
 */
export type UiEvent = { "type": "Rows", "value": Array<RepoRow> } | { "type": "BatchDone", "value": { id: BatchId, summary: BatchSummary, 
/**
 * `31 ok, 3 failed, 13 skipped in 4.2s`, from
 * [`BatchSummary::render`].
 */
line: string, } } | { "type": "Engine", "value": Event };
