// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";
import type { BatchSummary } from "./BatchSummary";
import type { Event } from "./Event";
import type { RepoRow } from "./RepoRow";

/**
 * What the webview receives.
 *
 * Everything the engine publishes, except that snapshots arrive as **rows**:
 * the grid needs the derived `Badge` for display and for its default sort, and
 * deriving it in TypeScript would put a piece of the domain in the frontend.
 *
 * A wrapper rather than a parallel copy of `Event`, so the enum's shape is
 * written down once and a passthrough arm cannot fall behind it.
 */
export type UiEvent = { "type": "Rows", "value": Array<RepoRow> } | { "type": "BatchDone", "value": { id: BatchId, summary: BatchSummary, 
/**
 * `31 ok, 3 failed, 13 skipped in 4.2s`, from
 * [`BatchSummary::render`].
 */
line: string, } } | { "type": "Engine", "value": Event };
