// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AheadBehind } from "./AheadBehind";

/**
 * Where the current branch stands against its configured upstream.
 */
export type Upstream = { 
/**
 * The remote's name — `"origin"`. What a targeted fetch fetches.
 */
remote: string, 
/**
 * The short tracking ref — `"origin/main"`.
 */
remote_ref: string, 
/**
 * `None` when the upstream is configured but its remote-tracking ref does
 * not exist. Deliberately not `ahead: 0, behind: 0`: "the branch it tracks
 * was deleted" and "in sync" are opposite facts, and an `Option` makes
 * reading one as the other a compile error rather than a quiet
 * reassurance.
 */
sync: AheadBehind | null, 
/**
 * Mtime of `FETCH_HEAD`: somebody fetched, including the user in their own
 * terminal. Distinct from [`FetchHealth::last_success`], which only this
 * tool's scheduler writes.
 */
last_fetch: number | null, };
