// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Path counts, by which side of the index they differ on.
 */
export type WorkTree = { 
/**
 * Index vs `HEAD`.
 */
staged: number, 
/**
 * Worktree vs index.
 */
modified: number, untracked: number, conflicted: number, };
