#!/usr/bin/env bash
#
# Generate the TypeScript types the shell talks to, from the Rust types that
# define them.
#
#   scripts/bindings.sh            regenerate apps/desktop/src/bindings
#   scripts/bindings.sh --check    fail if the committed output is stale
#
# The `--check` mode is the point. Not hand-writing duplicate types only helps
# if the generated ones are actually regenerated — a checked-in artefact nobody
# re-runs drifts exactly like a hand-written one, just more quietly.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
dest="$root/apps/desktop/src/bindings"

generate() {
  local out="$1"
  rm -rf "$out"
  mkdir -p "$out"
  # ts-rs writes its files from `#[ts(export)]` during a test run. Output is
  # held back unless it fails: the run emits a "failed to parse serde attribute
  # | transparent" warning per newtype, which ts-rs does not understand and does
  # not need to — it maps newtypes to their inner type correctly regardless.
  local log
  log="$(mktemp)"
  if ! TS_RS_EXPORT_DIR="$out" cargo test --manifest-path "$root/Cargo.toml" \
    -p git-scylla-core -p git-scylla-engine -p git-scylla-desktop \
    --features git-scylla-core/ts,git-scylla-engine/ts,git-scylla-desktop/ts \
    export_bindings >"$log" 2>&1; then
    cat "$log" >&2
    rm -f "$log"
    return 1
  fi
  rm -f "$log"

  # A barrel, generated here rather than written by hand for the same reason as
  # everything else in this directory.
  {
    echo "// Generated by scripts/bindings.sh. Do not edit."
    echo "//"
    echo "// Re-export of every type that crosses the Tauri boundary."
    for f in "$out"/*.ts; do
      name="$(basename "$f" .ts)"
      [ "$name" = "index" ] && continue
      echo "export type { $name } from \"./$name\";"
    done
  } > "$out/index.ts"
}

if [ "${1:-}" = "--check" ]; then
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  generate "$tmp/bindings"
  if ! diff -ru "$dest" "$tmp/bindings" >/dev/null 2>&1; then
    echo "TypeScript bindings are stale. Run scripts/bindings.sh and commit the result." >&2
    diff -ru "$dest" "$tmp/bindings" || true
    exit 1
  fi
  echo "bindings up to date"
else
  generate "$dest"
  echo "wrote $(ls "$dest" | wc -l | tr -d ' ') files to $dest"
fi
